routes/web.php
<?php

use app\Http\Controllers\cAsistenciaController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::resource('cAsistencia', App\Http\Controllers\cAsistenciaController::class)->middleware('auth');
Route::resource('instructor', App\Http\Controllers\InstructorController::class)->middleware('auth');
Route::resource('aprendiz', App\Http\Controllers\AprendizController::class)->middleware('auth');
Route::resource('asistencia', App\Http\Controllers\AsistenciaController::class)->middleware('auth');
Route::resource('rol', App\Http\Controllers\RolController::class)->middleware('auth');
Route::resource('actividad', App\Http\Controllers\ActividadController::class)->middleware('auth');
Route::resource('programa', App\Http\Controllers\ProgramaController::class)->middleware('auth');
Route::resource('tAsistencia', App\Http\Controllers\tAsistenciaController::class)->middleware('auth');
Route::resource('regAsistencia', App\Http\Controllers\RegAsistenciaController::class)->middleware('auth');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/tAsistencia.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class tAsistencia extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tAprendizs = Aprendiz::all();
        return view('tAsistencia.index', compact('tAprendizs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tAsistencia = new tAsistencia();
        return view('tAsistencia.create', compact('tAsistencia'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Aprendiz::$rules);

        $tAsistencia = tAsistencia::create($request->all());

        return redirect()->route('tAsistencia.index')
            ->with('success', 'Asistencia created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tAsistencia = Aprendiz::join('asistencias','asistencias.aprendizs_id','=','aprendizs.id')  
        ->select('aprendizs.nombreAprendiz','asistencias.asiste','asistencias.fecha_asiste')
        ->where('asistencias.id','=',$id)
        ->get();
        
        return view('Asistencia.show', compact('tAsistencia'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tAsistencia = Aprendiz::join('asistencias','asistencias.aprendizs_id','=','aprendizs.id')  
        ->select('aprendizs.nombreAprendiz','asistencias.asiste','asistencias.fecha_asiste')
        ->where('asistencias.id','=',$id)
        ->get();

        return view('tAsistencia.edit', compact('tAsistencia'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  tAsistencia $tAsistencia
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Aprendiz $tAsistencia)
    {
        request()->validate(Aprendiz::$rules);

        $tAsistencia->update($request->all());

        return redirect()->route('tAsistencia.index')
            ->with('success', 'Asistencia updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $tAsistencia = tAsistencia::find($id)->delete();

        return redirect()->route('tAsistencia.index')
            ->with('success', 'tAsistencia deleted successfully');
    }
}

app/Http/Controllers/tAsistenciaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Aprendiz;
use App\Models\Asistencia;
use App\Models\Programa;
use App\Models\Instructor;
use App\Models\regAsistencia;
use Illuminate\Http\Request;

/**
 * Class tAsistenciaController
 * @package App\Http\Controllers
 */
class tAsistenciaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tAprendizs = Aprendiz::all();
        $tProgramas = Programa::all();
        $tInstructors = Instructor::all();
        /*$tAsistencias = Aprendiz::join('asistencias','asistencias.aprendizs_id','=','aprendizs.id') 
        ->select('asistencias.id as id','aprendizs.nombreAprendiz','asistencias.asiste','asistencias.fecha_asiste','aprendizs.id as idAprendiz') 
        ->get();*/
        //return $tAprendizs;
        return view('tAsistencia.index', compact('tAprendizs','tProgramas','tInstructors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tAsistencia = new tAsistencia();
        return view('tAsistencia.create', compact('tAsistencia'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(regAsistencia::$rules);
        $tAprendizs = Aprendiz::all();
        $tProgramas = Programa::all();
        $tInstructors = Instructor::all();

        //return request();

        return redirect()->route('tAsistencia.index', compact('tAprendizs','tProgramas','tInstructors'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tAsistencia = Aprendiz::join('asistencias','asistencias.aprendizs_id','=','aprendizs.id')  
        ->select('aprendizs.nombreAprendiz','asistencias.asiste','asistencias.fecha_asiste')
        ->where('asistencias.id','=',$id)
        ->get();
        
        return view('Asistencia.show', compact('tAsistencia'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tAsistencia = Aprendiz::join('asistencias','asistencias.aprendizs_id','=','aprendizs.id')  
        ->select('aprendizs.nombreAprendiz','asistencias.asiste','asistencias.fecha_asiste')
        ->where('asistencias.id','=',$id)
        ->get();

        return view('tAsistencia.edit', compact('tAsistencia'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  tAsistencia $tAsistencia
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Aprendiz $tAsistencia)
    {
        request()->validate(Aprendiz::$rules);

        $tAsistencia->update($request->all());

        return redirect()->route('tAsistencia.index')
            ->with('success', 'Asistencia updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $tAsistencia = tAsistencia::find($id)->delete();

        return redirect()->route('tAsistencia.index')
            ->with('success', 'tAsistencia deleted successfully');
    }

    function saveAttendanceData($date, $employees)
{
    deleteAttendanceDataByDate($date);
    $db = getDatabase();
    $db->beginTransaction();
    $statement = $db->prepare("INSERT INTO reg_Asistencias(employee_id, date, status) VALUES (?, ?, ?)");
    foreach ($employees as $employee) {
        $statement->execute([$employee->id, $date, $employee->status]);
    }
    $db->commit();
    return true;
}

}

resources/views/tAsistencia/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Programa
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Programa</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('tAsistencia.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('tAsistencia.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/tAsistencia/form.blade.php
@extends('layouts.app')

@section('template_title')
Asistencia
@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <div style="display: flex; justify-content: space-between; align-items: center;">

                        <span id="card_title">
                            {{ __('Asistencia') }}
                        </span>

                        <div class="float-right">
                            <a href="{{ route('asistencia.create') }}" class="btn btn-primary btn-sm float-right" data-placement="left">
                                {{ __('Create New') }}
                            </a>
                        </div>
                    </div>
                </div>
                @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
                @endif

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover">
                            <thead class="thead">
                                <tr>
                                    <th>No</th>

                                    <th>Nombre Aprendiz</th>
                                    <th>Asiste</th>
                                    <th>Programa</th>
                                    <th>Instructor</th>

                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($tAprendizs as $tAprendiz)
                                <tr>
                                    <td>{{ $tAprendiz->id }}</td>

                                    <td>{{ $tAprendiz->NombreAprendiz }}</td>
                                    <td>
                                        <select name="Asistencia">
                                            <option value="X">X</option>
                                            <option value="A">A</option>
                                            <option value="E">E</option>
                                            <option value="R">R</option>
                                        </select>
                                    </td>
                                    <td>
                                        <select name="Asistencia">
                                            @foreach ($tProgramas as $tPrograma)
                                            <option value="{{ $tPrograma->id }}">{{ $tPrograma->Nombre_Programa }}</option>
                                            @endforeach
                                        </select>
                                    </td>
                                    <td>
                                        <select name="Asistencia">
                                            @foreach ($tInstructors as $tInstructor)
                                            <option value="{{ $tInstructor->id }}">{{ $tInstructor->NombreInstructor }}</option>
                                            @endforeach
                                        </select>
                                    </td>
                                    <td>
                                        <form action="{{ route('tAsistencia.destroy',$tAprendiz->id) }}" method="POST">
                                            <a class="btn btn-sm btn-primary " href="{{ route('tAsistencia.show',$tAprendiz->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                            <a class="btn btn-sm btn-success" href="{{ route('tAsistencia.edit',$tAprendiz->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Delete</button>
                                        </form>
                                    </td>

                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<div class="card-header">
    <div style="display: flex; justify-content: space-between; align-items: center;">
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>

    </div>
</div>
</div>


</div>
</div>
</div>
</div>
@endsection

resources/views/tAsistencia/index.blade.php
@extends('layouts.app')

@section('template_title')
Asistencia
@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <div style="display: flex; justify-content: space-between; align-items: center;">

                        <span id="card_title">
                            {{ __('Asistencia') }}
                        </span>

                        <div class="float-right">
                            <a href="{{ route('tAsistencia.create') }}" class="btn btn-primary btn-sm float-right" data-placement="left">
                                {{ __('Create New') }}
                            </a>
                        </div>
                    </div>
                </div>
                @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <p>{{ $message }}</p>
                </div>
                @endif

                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover">
                            <thead class="thead">
                                <tr>
                                    <th>No</th>

                                    <th>Nombre Aprendiz</th>
                                    <th>Asiste</th>
                                    <th>Programa</th>
                                    <th>Instructor</th>

                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($tAprendizs as $tAprendiz)
                                <tr>
                                    <td>{{ $tAprendiz->id }}</td>

                                    <td>{{ $tAprendiz->NombreAprendiz }}</td>
                                    <td>
                                        <select name="Asistencia">
                                            <option value="X">X</option>
                                            <option value="A">A</option>
                                            <option value="E">E</option>
                                            <option value="R">R</option>
                                        </select>
                                    </td>
                                    <td>
                                        <select name="Asistencia">
                                            @foreach ($tProgramas as $tPrograma)
                                            <option value="{{ $tPrograma->id }}">{{ $tPrograma->Nombre_Programa }}</option>
                                            @endforeach
                                        </select>
                                    </td>
                                    <td>
                                        <select name="Asistencia">
                                            @foreach ($tInstructors as $tInstructor)
                                            <option value="{{ $tInstructor->id }}">{{ $tInstructor->NombreInstructor }}</option>
                                            @endforeach
                                        </select>
                                    </td>
                                    <td>
                                        <form action="{{ route('tAsistencia.destroy',$tAprendiz->id) }}" method="POST">
                                            <a class="btn btn-sm btn-primary " href="{{ route('tAsistencia.show',$tAprendiz->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                            <a class="btn btn-sm btn-success" href="{{ route('tAsistencia.edit',$tAprendiz->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Delete</button>
                                        </form>
                                    </td>

                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<div class="card-header">
    <div style="display: flex; justify-content: space-between; align-items: center;">
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    </div>
</div>
</div>


</div>
</div>
</div>
</div>
@endsection