routes/web.php
<?php

use app\Http\Controllers\cAsistenciaController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::resource('cAsistencia', App\Http\Controllers\cAsistenciaController::class)->middleware('auth');
Route::resource('instructor', App\Http\Controllers\InstructorController::class)->middleware('auth');
Route::resource('aprendiz', App\Http\Controllers\AprendizController::class)->middleware('auth');
Route::resource('asistencia', App\Http\Controllers\AsistenciaController::class)->middleware('auth');
Route::resource('rol', App\Http\Controllers\RolController::class)->middleware('auth');
Route::resource('actividad', App\Http\Controllers\ActividadController::class)->middleware('auth');
Route::resource('programa', App\Http\Controllers\ProgramaController::class)->middleware('auth');
Route::resource('tAsistencia', App\Http\Controllers\tAsistenciaController::class)->middleware('auth');
Route::resource('regAsistencia', App\Http\Controllers\RegAsistenciaController::class)->middleware('auth');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Aprendiz.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Aprendiz
 *
 * @property $id
 * @property $NombreAprendiz
 * @property $ApellidoAprendiz
 * @property $TipoDocumentoAprendiz
 * @property $DocumentoAprendiz
 * @property $asistencias_id
 * @property $users_id
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Aprendiz extends Model
{
    
    static $rules = [
		'NombreAprendiz' => 'required',
		'ApellidoAprendiz' => 'required',
		'TipoDocumentoAprendiz' => 'required',
		'DocumentoAprendiz' => 'required',
		'asistencias_id' => 'required',
		'users_id' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['NombreAprendiz','ApellidoAprendiz','TipoDocumentoAprendiz','DocumentoAprendiz','asistencias_id','users_id'];



}

app/Http/Controllers/AprendizController.php
<?php

namespace App\Http\Controllers;

use App\Models\Aprendiz;
use Illuminate\Http\Request;

/**
 * Class AprendizController
 * @package App\Http\Controllers
 */
class AprendizController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $aprendizs = Aprendiz::paginate();

        return view('aprendiz.index', compact('aprendizs'))
            ->with('i', (request()->input('page', 1) - 1) * $aprendizs->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $aprendiz = new Aprendiz();
        return view('aprendiz.create', compact('aprendiz'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Aprendiz::$rules);

        $aprendiz = Aprendiz::create($request->all());

        return redirect()->route('aprendiz.index')
            ->with('success', 'Aprendiz created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $aprendiz = Aprendiz::find($id);

        return view('aprendiz.show', compact('aprendiz'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $aprendiz = Aprendiz::find($id);

        return view('aprendiz.edit', compact('aprendiz'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Aprendiz $aprendiz
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Aprendiz $aprendiz)
    {
        request()->validate(Aprendiz::$rules);

        $aprendiz->update($request->all());

        return redirect()->route('aprendiz.index')
            ->with('success', 'Aprendiz updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $aprendiz = Aprendiz::find($id)->delete();

        return redirect()->route('aprendiz.index')
            ->with('success', 'Aprendiz deleted successfully');
    }
}

resources/views/aprendiz/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Aprendiz
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Aprendiz</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('aprendiz.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('aprendiz.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/aprendiz/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Aprendiz
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Aprendiz</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('aprendiz.update', $aprendiz->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('aprendiz.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/aprendiz/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('NombreAprendiz') }}
            {{ Form::text('NombreAprendiz', $aprendiz->NombreAprendiz, ['class' => 'form-control' . ($errors->has('NombreAprendiz') ? ' is-invalid' : ''), 'placeholder' => 'Nombreaprendiz']) }}
            {!! $errors->first('NombreAprendiz', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('ApellidoAprendiz') }}
            {{ Form::text('ApellidoAprendiz', $aprendiz->ApellidoAprendiz, ['class' => 'form-control' . ($errors->has('ApellidoAprendiz') ? ' is-invalid' : ''), 'placeholder' => 'Apellidoaprendiz']) }}
            {!! $errors->first('ApellidoAprendiz', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('TipoDocumentoAprendiz') }}
            {{ Form::text('TipoDocumentoAprendiz', $aprendiz->TipoDocumentoAprendiz, ['class' => 'form-control' . ($errors->has('TipoDocumentoAprendiz') ? ' is-invalid' : ''), 'placeholder' => 'Tipodocumentoaprendiz']) }}
            {!! $errors->first('TipoDocumentoAprendiz', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('DocumentoAprendiz') }}
            {{ Form::text('DocumentoAprendiz', $aprendiz->DocumentoAprendiz, ['class' => 'form-control' . ($errors->has('DocumentoAprendiz') ? ' is-invalid' : ''), 'placeholder' => 'Documentoaprendiz']) }}
            {!! $errors->first('DocumentoAprendiz', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('asistencias_id') }}
            {{ Form::text('asistencias_id', $aprendiz->asistencias_id, ['class' => 'form-control' . ($errors->has('asistencias_id') ? ' is-invalid' : ''), 'placeholder' => 'Asistencias Id']) }}
            {!! $errors->first('asistencias_id', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('users_id') }}
            {{ Form::text('users_id', $aprendiz->users_id, ['class' => 'form-control' . ($errors->has('users_id') ? ' is-invalid' : ''), 'placeholder' => 'Users Id']) }}
            {!! $errors->first('users_id', '<div class="invalid-feedback">:message</p>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/aprendiz/index.blade.php
@extends('layouts.app')

@section('template_title')
    Aprendiz
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Aprendiz') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('aprendiz.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Create New') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>
                                        
										<th>Nombreaprendiz</th>
										<th>Apellidoaprendiz</th>
										<th>Tipodocumentoaprendiz</th>
										<th>Documentoaprendiz</th>
										<th>Asistencias Id</th>
										<th>Users Id</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($aprendizs as $aprendiz)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>{{ $aprendiz->NombreAprendiz }}</td>
											<td>{{ $aprendiz->ApellidoAprendiz }}</td>
											<td>{{ $aprendiz->TipoDocumentoAprendiz }}</td>
											<td>{{ $aprendiz->DocumentoAprendiz }}</td>
											<td>{{ $aprendiz->asistencias_id }}</td>
											<td>{{ $aprendiz->users_id }}</td>

                                            <td>
                                                <form action="{{ route('aprendiz.destroy',$aprendiz->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('aprendiz.show',$aprendiz->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('aprendiz.edit',$aprendiz->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Delete</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $aprendizs->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/aprendiz/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $aprendiz->name ?? 'Show Aprendiz' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Aprendiz</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('aprendiz.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Nombreaprendiz:</strong>
                            {{ $aprendiz->NombreAprendiz }}
                        </div>
                        <div class="form-group">
                            <strong>Apellidoaprendiz:</strong>
                            {{ $aprendiz->ApellidoAprendiz }}
                        </div>
                        <div class="form-group">
                            <strong>Tipodocumentoaprendiz:</strong>
                            {{ $aprendiz->TipoDocumentoAprendiz }}
                        </div>
                        <div class="form-group">
                            <strong>Documentoaprendiz:</strong>
                            {{ $aprendiz->DocumentoAprendiz }}
                        </div>
                        <div class="form-group">
                            <strong>Asistencias Id:</strong>
                            {{ $aprendiz->asistencias_id }}
                        </div>
                        <div class="form-group">
                            <strong>Users Id:</strong>
                            {{ $aprendiz->users_id }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection