routes/web.php
<?php

use app\Http\Controllers\cAsistenciaController;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::resource('cAsistencia', App\Http\Controllers\cAsistenciaController::class)->middleware('auth');
Route::resource('instructor', App\Http\Controllers\InstructorController::class)->middleware('auth');
Route::resource('aprendiz', App\Http\Controllers\AprendizController::class)->middleware('auth');
Route::resource('asistencia', App\Http\Controllers\AsistenciaController::class)->middleware('auth');
Route::resource('rol', App\Http\Controllers\RolController::class)->middleware('auth');
Route::resource('actividad', App\Http\Controllers\ActividadController::class)->middleware('auth');
Route::resource('programa', App\Http\Controllers\ProgramaController::class)->middleware('auth');
Route::resource('tAsistencia', App\Http\Controllers\tAsistenciaController::class)->middleware('auth');
Route::resource('regAsistencia', App\Http\Controllers\RegAsistenciaController::class)->middleware('auth');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/cAsistenciaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Aprendiz;
use Illuminate\Http\Request;

/**
 * Class cAsistenciaController
 * @package App\Http\Controllers
 */
class CAsistenciaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $cAsistencias = Aprendiz::join('asistencias','asistencias.aprendizs_id','=','aprendizs.id') 
        ->select('asistencias.id as id','aprendizs.nombreAprendiz','asistencias.asiste','asistencias.fecha_asiste','aprendizs.id as idAprendiz') 
        ->get();
        //return $tAprendiz + "," +  $tAsistencias;
        return view('cAsistencia.index', compact('cAsistencias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cAsistencia = new cAsistencia();
        return view('cAsistencia.create', compact('cAsistencia'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Aprendiz::$rules);

        $cAsistencia = cAsistencia::create($request->all());

        return redirect()->route('cAsistencia.index')
            ->with('success', 'cAsistencia created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $cAsistencia = Aprendiz::join('asistencias','asistencias.aprendizs_id','=','aprendizs.id')  
        ->select('aprendizs.nombreAprendiz','asistencias.asiste','asistencias.fecha_asiste')
        ->where('asistencias.id','=',$id)
        ->get();
        
        return view('cAsistencia.show', compact('cAsistencia'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cAsistencia = Aprendiz::join('asistencias','asistencias.aprendizs_id','=','aprendizs.id')  
        ->select('aprendizs.nombreAprendiz','asistencias.asiste','asistencias.fecha_asiste')
        ->where('asistencias.id','=',$id)
        ->get();

        return view('cAsistencia.edit', compact('cAsistencia'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  cAsistencia $cAsistencia
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Aprendiz $cAsistencia)
    {
        request()->validate(Aprendiz::$rules);

        $cAsistencia->update($request->all());

        return redirect()->route('cAsistencia.index')
            ->with('success', 'Asistencia updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $cAsistencia = cAsistencia::find($id)->delete();

        return redirect()->route('cAsistencia.index')
            ->with('success', 'cAsistencia deleted successfully');
    }
}

resources/views/cAsistencia/create.blade.php
@extends('layouts.app')

@section('template_title')
    Create Asistencia
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Create Asistencia</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('cAsistencia.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('asistencia.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/cAsistencia/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Asistencia
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Asistencia</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('cAsistencia.update', $cAsistencia->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('cAsistencia.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/cAsistencia/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('NombreAprendiz') }}
            {{ Form::text('NombreAprendiz', $cAsistencia->NombreAprendiz, ['class' => 'form-control' . ($errors->has('NombreAprendiz') ? ' is-invalid' : ''), 'placeholder' => 'Nombreaprendiz']) }}
            {!! $errors->first('NombreAprendiz', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Asiste') }}
            {{ Form::text('Asiste', $cAsistencia->cAsistencia, ['class' => 'form-control' . ($errors->has('Asiste') ? ' is-invalid' : ''), 'placeholder' => 'Asiste']) }}
            {!! $errors->first('Asiste', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Fecha_Asiste') }}
            {{ Form::text('Fecha_Asiste', $cAsistencia->Fecha_Asiste, ['class' => 'form-control' . ($errors->has('Fecha_Asiste') ? ' is-invalid' : ''), 'placeholder' => 'Fecha Asiste']) }}
            {!! $errors->first('Fecha_Asiste', '<div class="invalid-feedback">:message</p>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/cAsistencia/index.blade.php
@extends('layouts.app')

@section('template_title')
    Asistencia
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Asistencia') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('asistencia.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Create New') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>
                                        
										<th>Nombre Aprendiz</th>
                                        <th>Asiste</th>
										<th>Fecha Asiste</th>
                                        <th>id Aprendiz</th>
										

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($cAsistencias as $cAsistencia)
                                        <tr>
                                            <td>{{ $cAsistencia->id }}</td>
                                            
                                            <td>{{ $cAsistencia->nombreAprendiz }}</td>
											<td>{{ $cAsistencia->asiste }}</td>
											<td>{{ $cAsistencia->fecha_asiste }}</td>
                                            <td>{{ $cAsistencia->idAprendiz }}</td>

                                            <td>
                                                <form action="{{ route('cAsistencia.destroy',$cAsistencia->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('cAsistencia.show',$cAsistencia->id) }}"><i class="fa fa-fw fa-eye"></i> Show</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('cAsistencia.edit',$cAsistencia->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Delete</button>
                                                </form>
                                            </td>

                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cAsistencia/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $asistencia->name ?? 'Show Asistencia' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Asistencia</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('asistencia.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                    
                    <div class="form-group">
                            <strong>Nombre del aprendiz:</strong>
                            {{ $cAsistencia->nombreAprendiz }}
                        </div>
                        
                        <div class="form-group">
                            <strong>Asiste:</strong>
                            {{ $cAsistencia->asiste }}
                        </div>
                        <div class="form-group">
                            <strong>Fecha Asiste:</strong>
                            {{ $cAsistencia->fecha_asiste }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection